Removing json as a dependency
json is installed by default, and pip throws errors during installation because of it:
ERROR: Could not find a version that satisfies the requirement json (from -r /opt/cyops-integrations/integrations/connectors/csv-data-management_1_0_0/requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for json (from -r /opt/cyops-integrations/integrations/connectors/csv-data-management_1_0_0/requirements.txt (line 4))